# Site settings
title: FEI, Xiaohan
email: feixh at cs dot ucla dot edu
description: > # this means to ignore newlines until "baseurl:"
  his is Xiaohan's personal website powered by Jekyll and GitHub.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://feixh.github.com" # the base hostname & protocol for your site
# twitter_username:
github_username:  feixh

# Build settings
markdown: kramdown

# page lists
pages: [Posts]
pages: [Projects]
